Swift3
giginet/CustomKeyboardTextField pull request #2
Opened 2016-12-01 17:55 UTC by jollyjoester

Please review 😃

2016-12-02 05:07 UTC, giginet commented
Thank you for your contribution 🙏 

I'll review this PR in this weekend
Please moment.

2016-12-02 07:03 UTC, jollyjoester commented
Oops... I forgot removing Xcode7.3.1 environment in TravisCI.
I'll do it later.

2016-12-03 14:45 UTC, giginet requested changes
Some access control attributes should be closer.

And please fix CI.
You should drop Xcode 7.x support then It might be fixed

2016-12-03 14:45 UTC, giginet commented on CustomKeyboardTextFieldDemo/CustomKeyboard.swift
> +    fileprivate func iconView(_ row: Int) -> UIImageView {
`private`

2016-12-03 14:45 UTC, giginet commented on CustomKeyboardTextFieldDemo/CustomKeyboard.swift
> +    fileprivate func updateTextField(for row: Int) {
`private`

2016-12-03 14:45 UTC, giginet commented on CustomKeyboardTextFieldDemo/CustomKeyboard.swift
> +    fileprivate func insertText(_ insertText: String) {
`private`

2016-12-03 14:45 UTC, giginet commented on Sources/CustomKeyboardTextField.swift
> +    fileprivate func setupCustomKeyboard() {
`private`

2016-12-03 14:45 UTC, giginet commented on Sources/CustomKeyboardTextField.swift
> +    fileprivate(set) var customKeyboardView: CustomKeyboardView? {
private

2016-12-03 14:45 UTC, giginet commented on Sources/CustomKeyboardTextField.swift
> +    fileprivate(set) var customKeyboardAccessoryView: CustomKeyboardAccessoryView? {
private

2016-12-03 14:45 UTC, giginet commented on Sources/Keyboards/ToolbarAccessoryView.swift
> +    weak open var textField: UITextField? = nil
`public`

2016-12-03 14:45 UTC, giginet commented on Sources/Keyboards/UIDatePickerKeyboard.swift
> +    open let datePickerKeyboardDataSource: DataSource
public

2016-12-03 14:45 UTC, giginet commented on Sources/Keyboards/UIDatePickerKeyboard.swift
> +    weak open var textField: UITextField? = nil
public

2016-12-03 14:45 UTC, giginet commented on Sources/Keyboards/UIPickerViewKeyboard.swift
> +    open let pickerKeyboardDataSource: DataSource
public

2016-12-03 14:45 UTC, giginet commented on Sources/Keyboards/UIPickerViewKeyboard.swift
> +    weak open var textField: UITextField? = nil
public

2016-12-06 17:43 UTC, jollyjoester commented
I fixed my code that you pointed out.
And I'm not familiar with TravisCI, so please check .travis.yml.

2016-12-07 01:53 UTC, giginet commented
Thank you!

According to Travis CI output.
This class must be `open`. https://github.com/giginet/CustomKeyboardTextField/pull/2/commits/594287306ed19a2f4271868168b60f2824e19c57#diff-c99e96a90d698f7e9e026db431402453R15

I meant you should fix only properties, not this class.

I apologize confused you. Could you fix this?

2016-12-07 03:58 UTC, jollyjoester commented
I'll continue to fix TravisCI error. Just a moment, please.

2016-12-07 06:31 UTC, giginet commented
Thank you!!!!

CI is still fallen, however, I think it is caused because of building from the fork. 
Maybe, it will be fixed this branch is merged.

2016-12-07 06:31 UTC, giginet approved these changes

2016-12-07 06:31 UTC, merged

2016-12-07 07:45 UTC, jollyjoester commented
Thank you very much!